"""init tables

Revision ID: a0c4482484e7
Revises: 84613410a69c
Create Date: 2025-12-04 16:10:41.042109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0c4482484e7'
down_revision: Union[str, Sequence[str], None] = '84613410a69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_memories', sa.Column('memory_json', sa.JSON(), nullable=False))
    op.add_column('user_memories', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('uq_memory_unique'), 'user_memories', type_='unique')
    op.create_unique_constraint(None, 'user_memories', ['user_id'])
    op.drop_column('user_memories', 'memory_type')
    op.drop_column('user_memories', 'content')
    op.drop_column('user_memories', 'raw_json')
    op.drop_column('user_memories', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_memories', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('user_memories', sa.Column('raw_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_memories', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_memories', sa.Column('memory_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_memories', type_='unique')
    op.create_unique_constraint(op.f('uq_memory_unique'), 'user_memories', ['user_id', 'memory_type', 'content'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_memories', 'updated_at')
    op.drop_column('user_memories', 'memory_json')
    # ### end Alembic commands ###
