"""init tables

Revision ID: c38fc499adca
Revises: a82fc0870a8c
Create Date: 2025-12-04 14:26:43.432488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c38fc499adca'
down_revision: Union[str, Sequence[str], None] = 'a82fc0870a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_sessions', 'messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               comment=None,
               existing_comment="[{ role: 'user'|'assistant', text: '...', timestamp: '...' }]")
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.add_column('user_memories', sa.Column('memory_type', sa.String(), nullable=False))
    op.add_column('user_memories', sa.Column('content', sa.String(), nullable=False))
    op.add_column('user_memories', sa.Column('raw_json', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_user_memories_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.create_unique_constraint('uq_memory_unique', 'user_memories', ['user_id', 'memory_type', 'content'])
    op.drop_column('user_memories', 'updated_at')
    op.drop_column('user_memories', 'memory')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'created_at')
    op.add_column('user_memories', sa.Column('memory', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('user_memories', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_memory_unique', 'user_memories', type_='unique')
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_memories_id'), 'user_memories', ['id'], unique=False)
    op.drop_column('user_memories', 'raw_json')
    op.drop_column('user_memories', 'content')
    op.drop_column('user_memories', 'memory_type')
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chat_sessions', 'messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               comment="[{ role: 'user'|'assistant', text: '...', timestamp: '...' }]")
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
